# Generated by Django 2.2.6 on 2019-10-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('source_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipes', models.ManyToManyField(to='recipes.Recipe')),
            ],
        ),
    ]
