# Generated by Django 2.2.6 on 2019-10-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeSteps',
            new_name='RecipeStep',
        ),
    ]
