# Generated by Django 2.2.6 on 2019-10-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20191028_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_quantity',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient_quantity',
            field=models.CharField(max_length=42),
        ),
    ]
