# Generated by Django 2.2.6 on 2019-10-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img_url',
            field=models.URLField(default='http://meerasodha.com/wp-content/uploads/2016/04/coconut-prawns.png'),
            preserve_default=False,
        ),
    ]
