# Generated by Django 2.2.6 on 2019-10-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_quantity',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
